config/routes.rb
Ninja::Application.routes.draw do
    root to: "pages#home"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match 'home' => 'pages#home', as: :pages_home
  match 'contact' => 'pages#contact', as: :pages_contact 
  match 'myteam' => 'pages#myteam', as: :pages_myteam
  match 'progress' => 'pages#myteamprogress', as: :pages_myteamprogress
  match 'leaderboard' => 'pages#leaderboard', as: :pages_leaderboard  
  


  devise_for :users
  ActiveAdmin.routes(self)
    match '*code' => 'pages#checkcode'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/checkpoint.rb
class Checkpoint < ActiveRecord::Base
  attr_accessible :host_id, :location, :name, :points, :route, :task
  has_and_belongs_to_many :teams
end

app/models/checkpoints_teams.rb
class CheckpointsTeams < ActiveRecord::Base
  attr_accessible :checkpoint_id, :team_id
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name
  has_many :users
  has_and_belongs_to_many :checkpoints
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :handphone, :name, :school, :team_id

  belongs_to :team
  
  validates_presence_of :team, message: "Please eneter valid Tema ID"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!, except: [:home, :contact]
  def home
  end

  def contact
  end
  
  def myteam
    @myteam = current_user.team
  end
  
  def myteamprogress
    @myteam = current_user.team
    @totalpoints = 0;
    Checkpoint.all.each do |t|
      @totalpoints += t.points
    end
    @teampoints = 0;
    @myteam.checkpoints.each do |t|
      @teampoints += t.points
    end
    @width = @teampoints*100/@totalpoints
  end
  
  def checkpoints
    @checkpoints = Checkpoint.all
  end
  
  def checkcode
    m = Checkpoint.where("route = ?", params[:code]).first
    if m.nil?
      flash[:notice] = "That's an invalid code. Are you trying to scam us?"
      redirect_to root_path
    else
      t = current_user.team
      t.checkpoint_ids = t.checkpoint_ids.push(m.id)
      flash[:notice] = "That's a valid code! Well Done!"
      redirect_to pages_myteamprogress_path
    end
  end
  
  def leaderboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path, additional_classes)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => (class_name + additional_classes)) do
      link_to link_text, link_path
    end
  end
  
  def title(page_title)
    content_for(:title) { page_title }
  end
  
  def progress_width(t)
    totalpoints = 0;
    Checkpoint.all.each do |m|
      totalpoints += m.points
    end
    teampoints = 0;
    t.checkpoints.each do |z|
      teampoints += z.points
    end
    width = teampoints*100/totalpoints
    return width
  end
  
  def team_points(t)
    teampoints = 0;
    t.checkpoints.each do |z|
      teampoints += z.points
    end
    return teampoints
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "IDA Dojo" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
	<%= render 'partials/topbar.html.erb'%>
    <div class="row" id="container">
		<% flash.each do |name, msg| %>
			<div class="alert-box">
				<%= msg %>
			</div>
	      <% end %>
    	<%= yield %>
    </div>
	

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/checkpoints.html.erb
<h2 class="subheader">Checkpoints</h2>
<hr />

<% @checkpoints.each do|c,index| %>
	
	<p><%= c.name %></p>
	
<% end%>

<% if @checkpoints.count == 0 %>

<p>There are no checkpoints available.</p> 

<% end %>
	

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/leaderboard.html.erb
<h2 class="subheader">Leaderboard</h2>
<hr />

<% Team.all.each do |t| %>
	<div class="teamprogress" style="position:relative; margin-left:8px;">
		<div class="row"><p class="small-12 columns" style="margin-bottom:5px; font-weight: bold; font-size: 25px; padding-left: 25px; color:white; z-index:1000; "><%= t.name + " (" + team_points(t).to_s + ")"%></p></div>
		<div class="row" style="position:absolute; width:100%; top:0; z-index:1;">
			<div class="large-12 columns" style="padding-right:0;">
				<div class="progress progress-striped active">
				  <div class="bar" style="width: <%= progress_width(t) %>%;"></div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/pages/myteam.html.erb
<h2 class="subheader"><%= @myteam.name %></h2>
<hr />

<div class="hide-for-small">
	<table style="width:100%;">
		<thead>
			<tr>
				<th class="large-3 columns">Name</th>
				<th class="large-3 columns">Email</th>
				<th class="large-3 columns">School</th>
				<th class="large-3 columns">Handphone</th>
			</tr>
		</thead>
		<tbody>
			<% @myteam.users.order("name").each do|t| %>
			<tr>
				<td class="large-3 columns"><%= t.name %></td>
				<td class="large-3 columns"><%= t.email %></td>
				<td class="large-3 columns"><%= t.school %></td>
				<td class="large-3 columns"><%= t.handphone %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<div class="hide-for-medium-up">
	<div class="section-container accordion" data-section="accordion">
		<% @myteam.users.order("name").each do|t| %>
		<section>
			<p class="title" data-section-title><a href="#"><%= t.name %></a></p>
			<div class="content" data-section-content>
				<span><b>Email</b></span>
				<p><%= t.email %></p>
				<span><b>Handphone</b></span>
				<p><%= t.handphone %></p>
				<span><b>School</b></span>
				<p><%= t.school %></p>
			</div>
		</section>
		<% end %>
	</div>
</div>

app/views/pages/myteamprogress.html.erb
<h2 class="subheader"><%= @myteam.name + "'s Progress"%></h2>
<hr />

<div class="progress progress-striped active">
  <div class="bar" style="width: <%=@width%>%;"></div>
</div>


<h3 class="subheader">Completed Checkpoints (<%= @myteam.checkpoints.count.to_s + "/" + Checkpoint.count.to_s %>)</h3>
<hr />
<div class="hide-for-small">
	<table style="width:100%;">
		<thead>
			<tr>
				<th class="large-3 columns">Name</th>
				<th class="large-3 columns">Location</th>
				<th class="large-3 columns">Code</th>
				<th class="large-3 columns">Points</th>
			</tr>
		</thead>
		<tbody>
			<% @myteam.checkpoints.order("name").each do|t| %>
			<tr>
				<td class="large-3 columns"><%= t.name %></td>
				<td class="large-3 columns"><%= t.location %></td>
				<td class="large-3 columns"><%= t.route %></td>
				<td class="large-3 columns"><%= t.points %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<div class="hide-for-medium-up">
	<div class="section-container accordion" data-section="accordion">
		<% @myteam.checkpoints.order("name").each do|t| %>
		<section>
			<p class="title" data-section-title><a href="#"><%= t.name %></a></p>
			<div class="content" data-section-content>
				<span><b>Location</b></span>
				<p><%= t.location %></p>
				<span><b>Code</b></span>
				<p><%= t.route %></p>
				<span><b>Points</b></span>
				<p><%= t.points %></p>
			</div>
		</section>
		<% end %>
	</div>
</div>

app/views/partials/_topbar.html.erb
<div class="contain-to-grid sticky" style="height:45px">
	<nav class="top-bar">
		<ul class="title-area">
			<!-- Title Area -->
			<li class="name">
				<h1><%= link_to "IDA Dojo", root_path %></h1>
			</li>
			<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
			<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		</ul>

		<section class="top-bar-section">
			<!-- Left Nav Section -->
			<ul class="left">
				<li class="divider"></li>
				<%= nav_link "Home", root_path, ""%>
				<li class="divider"></li>
				<%= nav_link "Contact", pages_contact_path,"" %>
				<li class="divider"></li>
				<% if user_signed_in? %>
				<li><%= nav_link "Team Members", pages_myteam_path, ""  %></li>
				<li class="divider"></li>
				<li><%= nav_link "Team Progress", pages_myteamprogress_path, ""  %></li>
				<li class="divider"></li>

				<%= nav_link "Leaderboard", pages_leaderboard_path, "" %>
				<li class="divider"></li>
				<% end %>
			</ul>

			<!-- Right Nav Section -->
			<ul class="right">
				<% if user_signed_in? %>
				<%= nav_link "#{current_user.name.titleize}", edit_user_registration_path, ""%>
				<li class="divider"></li>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				<% else %>
				<%= nav_link "Sign up", new_user_registration_path, "" %>
				<li class="divider"></li>
				<%= nav_link "Login", new_user_session_path, "" %>	
				<% end %>
			</ul>
		</section>
	</nav>
</div>